javax:
    sql:
        DataSource:
            payment-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: payment-db
                    port: 3306
                    databaseName: payments
                    user: payment
                    password: pass
